apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi
spec:
  type: LoadBalancer # OrbStack will seamlessly expose this to your Mac's localhost
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000